### ISSUE TITLE
Set filename on start recording does not work (commented out in source code)

### ISSUE THREAD

**Issue by BigRoy** [Rokoko/rokoko-studio-live-unreal-engine#10]
### Issue

It seems [that the source code disables passing along a filename on Start Recording to the API](https://github.com/RokokoElectronics/rokoko-studio-live-unreal-engine/blob/7bbc7b71a9b122a1c0ec046bb8bf0003befc7099/Plugins/Smartsuit/Source/Smartsuit/Private/RokokoStudioCommandAPI.cpp#L66) which unfortunately disallows to record takes with a specific name, e.g. matching it with a name in the Take Recorder in Unreal Engine.

Uncommenting it and recompiling works as expected for my use case. However, the default Blueprint should be checked whether it still works with the default functionality.

**Comment by SergeiSolokhin** [comment]
the plugin command api support has been updated

**Comment by BigRoy** [comment]
That was quick. /jk - thanks for the notification!
