### ISSUE TITLE
documentation link 404s

### ISSUE THREAD

**Issue by bmahlbrand** [Rokoko/rokoko-studio-live-unreal-engine#14]
https://github.com/Rokoko/rokoko-studio-live-unreal-engine/blob/bce5f0a6f8cc0204c9435e80be8d4479a2717593/Plugins/Smartsuit/Smartsuit.uplugin#L11

![image](https://user-images.githubusercontent.com/5303952/96722401-569d8100-137b-11eb-8daf-e8e906af9cf9.png)

**Comment by SpirosK-RKK** [comment]
This will be fixed in the next versions.
Please use: https://github.com/Rokoko/rokoko-studio-live-unreal-engine/wiki/Rokoko-Studio-Live-Plugin-for-Unreal-Engine
