### ISSUE TITLE
latest doesn't build on 4.25

### ISSUE THREAD

**Issue by bmahlbrand** [Rokoko/rokoko-studio-live-unreal-engine#23]
I needed to add categories to the following functions shown here (USmartsuitBlueprintLibrary) in order to even compile this...
![image](https://user-images.githubusercontent.com/5303952/102389991-e2114800-3fa1-11eb-8581-d659acc8c011.png)

**Comment by ibrews** [comment]
doesn't build for me in 4.26 either. seems to be the same error. Did you figure out a workaround @bmahlbrand ?

**Comment by bmahlbrand** [comment]
Isn't this the workaround? If not I've long since forgotten...sorry :S

**Comment by ibrews** [comment]
Do you still have the SmartsuitBlueprintLibrary.cpp file? I just can't figure out where to put in the functions you snapshotted. thanks.

**Comment by Chris528** [comment]
which branch of the plugin are you using @ibrews ?

**Comment by ibrews** [comment]
hey Chris, it's Alex-- we solved all my plugin issues together yesterday!

This was using the .10 marketplace plugin. Confirming the GitHub plugin builds fine!

**Comment by SpirosK-RKK** [comment]
Closing based on the above.
