### ISSUE TITLE
The skeleton preset UI cannot be redisplayed

### ISSUE THREAD

**Issue by anuos123** [Rokoko/rokoko-studio-live-unreal-engine#35]
![image](https://user-images.githubusercontent.com/52443599/163711738-3f5ac64f-1623-4429-9b3a-4769a7a0027d.png)

**Comment by Chris528** [comment]
What version of the plugin are you using?

**Comment by SergeiSolokhin** [comment]
closing for now, feel free to open a new issue if that is still relevant
