### ISSUE TITLE
can not find receiver even placed receiver in scene

### ISSUE THREAD

**Issue by lucasjinreal** [Rokoko/rokoko-studio-live-unreal-engine#38]
<img width="735" alt="image" src="https://user-images.githubusercontent.com/21303438/189668982-7f808e24-0a06-46cc-88e5-71bfabe0db07.png">

debug the plugin, can not find recevier from this function. WHy?

<img width="570" alt="image" src="https://user-images.githubusercontent.com/21303438/189669060-dc5a974c-362b-445d-937f-a19b908e5239.png">

i already have it placed. Any thing else need to check?

**Comment by SergeiSolokhin** [comment]
receiver is depricated, please use live link settings instead
