### ISSUE TITLE
Root motion support non-existent?

### ISSUE THREAD

**Issue by perkele1989** [Rokoko/rokoko-studio-live-unreal-engine#39]
Is root motion missing from the UE integration? I can't find a root bone override in the bone map (and force adding one from "Root"->"root"  in C++ did nothing).

Have I missed a step in enabling this?

Best regards,

**Comment by SergeiSolokhin** [comment]
SmartsuitPoseNode has an option to enable a root motion extraction for a live streaming skeleton data.
